package app.revanced.bilibili.settings

import android.graphics.Color
import app.revanced.bilibili.content.BiliDocumentsProvider
import app.revanced.bilibili.utils.*

object Settings {
    @JvmField val Debug = BooleanSetting(key = "debug", needReboot = true)
    @JvmField val ShowHint = BooleanSetting(key = "show_hint")


    // region Group: 解锁番剧限制
    @JvmField val UnlockAreaLimit = BooleanSetting(key = "main_func")
    @JvmField val AllowDownload = BooleanSetting(key = "allow_download", dependency = UnlockAreaLimit)
    @JvmField val AllowMiniPlay = BooleanSetting(key = "allow_mini_play")
    @JvmField val TaiWanServer = StringSetting(key = "tw_server")
    @JvmField val HongKongServer = StringSetting(key = "hk_server")
    @JvmField val ChinaServer = StringSetting(key = "cn_server")
    @JvmField val ThailandServer = StringSetting(key = "th_server")
    @JvmField val UposHost = StringSetting(key = "upos_host")
    @JvmField val SaveThailandHistory =
        BooleanSetting(key = "save_th_history", defValue = true, dependency = UnlockAreaLimit)


    // region Group: 播放�?
    @JvmField val HalfScreenQuality = StringSetting(key = "half_screen_quality", defValue = "0")
    @JvmField val FullScreenQuality = StringSetting(key = "full_screen_quality", defValue = "0")
    @JvmField val MobileFullScreenQuality = StringSetting(key = "full_screen_quality_mobile", defValue = "0")
    @JvmField val PlayerVersion = StringSetting(key = "player_version", defValue = "0", needReboot = true)
    @JvmField val RememberLosslessSetting = BooleanSetting(key = "remember_lossless_setting")
    @JvmField val DefaultPlaybackSpeed = FloatSetting(key = "default_playback_speed")
    @JvmField val LongPressPlaybackSpeed = FloatSetting(key = "long_press_playback_speed")
    @JvmField val OverridePlaybackSpeed = StringSetting(key = "playback_speed_override", needReboot = true)
    @JvmField val TrialVipQuality = BooleanSetting(key = "trial_vip_quality")
    @JvmField val UnlimitedTrialQuality = BooleanSetting(key = "unlimited_trial_quality")
    @JvmField val DisableSegmentedSection = BooleanSetting(key = "disable_segmented_section")
    @JvmField val DisableAutoNextPlay = BooleanSetting(key = "disable_auto_next_play")
    @JvmField val DisablePlayerLongPress = BooleanSetting(key = "disable_player_long_press")
    @JvmField val ScaleToSwitchRatio = BooleanSetting(key = "scale_to_switch_ratio")
    @JvmField val ForceHwCodec = BooleanSetting(key = "force_hw_codec")
    @JvmField val ForceHdr = BooleanSetting(key = "force_hdr")
    @JvmField val DisableP2PUpload = BooleanSetting(key = "disable_p2p_upload", needReboot = true)
    @JvmField val PreferStableCdn = BooleanSetting(key = "prefer_stable_cdn", needReboot = true)
    @JvmField val AccessKeyMain = StringSetting(key = "access_key_main")
    @JvmField val AccessKeyThailand = StringSetting(key = "access_key_th")
    @JvmField val RememberPlaybackSpeed = BooleanSetting(key = "remember_playback_speed")
        @JvmField val AutoEnterPip = BooleanSetting(key = "auto_enter_pip")
        @JvmField val PipAspectRatio = IntSetting(key = "pip_aspect_ratio", defValue = 0)
        @JvmField val DoubleTapSeekTime = IntSetting(key = "double_tap_seek_time", defValue = 10)
        @JvmField val PlaybackStatsOverlay = BooleanSetting(key = "playback_stats_overlay")
        @JvmField val QuickFavorite = BooleanSetting(key = "quick_favorite")
        @JvmField val CommentPinchZoom = BooleanSetting(key = "comment_pinch_zoom")
        @JvmField val ShareWithTimestamp = BooleanSetting(key = "share_with_timestamp")
        @JvmField val WatchStats = BooleanSetting(key = "watch_stats")
        @JvmField val LoopInterval = IntSetting(key = "loop_interval", defValue = 0)
        @JvmField val ScreenshotTimestamp = BooleanSetting(key = "screenshot_timestamp")
        @JvmField val SwipeGestureCustom = BooleanSetting(key = "swipe_gesture_custom")
        @JvmField val AutoNightMode = BooleanSetting(key = "auto_night_mode")
        @JvmField val QualityBadge = BooleanSetting(key = "quality_badge")
        @JvmField val PlayerClock = BooleanSetting(key = "player_clock")
        @JvmField val VolumeBoost = BooleanSetting(key = "volume_boost")
        @JvmField val VolumeBoostLevel = IntSetting(key = "volume_boost_level", defValue = 100)
        @JvmField val CommentDraft = BooleanSetting(key = "comment_draft")
        @JvmField val VideoMirror = BooleanSetting(key = "video_mirror")
        @JvmField val BrightnessLock = BooleanSetting(key = "brightness_lock")
        @JvmField val CommentHighlightUp = BooleanSetting(key = "comment_highlight_up")
        @JvmField val AutoRotate = BooleanSetting(key = "auto_rotate")
        @JvmField val DanmakuMerge = BooleanSetting(key = "danmaku_merge")
        @JvmField val TouchLock = BooleanSetting(key = "touch_lock")
        @JvmField val PlayerBattery = BooleanSetting(key = "player_battery")
        @JvmField val DanmakuFontBorder = BooleanSetting(key = "danmaku_font_border")
        @JvmField val CommentCollapse = BooleanSetting(key = "comment_collapse")
        @JvmField val CommentCollapseLines = IntSetting(key = "comment_collapse_lines", defValue = 5)
        @JvmField val VideoCrop = BooleanSetting(key = "video_crop")
        @JvmField val DanmakuSendFont = IntSetting(key = "danmaku_send_font", defValue = 25)
        @JvmField val AutoResume = BooleanSetting(key = "auto_resume")
        @JvmField val CommentFilterLevel = IntSetting(key = "comment_filter_level", defValue = 0)
        @JvmField val LiveGiftBlock = BooleanSetting(key = "live_gift_block")
        @JvmField val DanmakuSendColor = IntSetting(key = "danmaku_send_color", defValue = 0xFFFFFF)
        @JvmField val DanmakuSpeedSync = BooleanSetting(key = "danmaku_speed_sync")
        @JvmField val VideoPreload = BooleanSetting(key = "video_preload")
        @JvmField val HomeTabReorder = BooleanSetting(key = "home_tab_reorder")
        @JvmField val SubtitleFont = StringSetting(key = "subtitle_font", defValue = "default")
        @JvmField val DoubleTapAction = IntSetting(key = "double_tap_action", defValue = 0)
        @JvmField val VideoWatermark = BooleanSetting(key = "video_watermark")
        @JvmField val DanmakuShadow = BooleanSetting(key = "danmaku_shadow")
        @JvmField val AutoSkipAds = BooleanSetting(key = "auto_skip_ads")
        @JvmField val VideoChapters = BooleanSetting(key = "video_chapters")
        @JvmField val CommentSortHot = BooleanSetting(key = "comment_sort_hot")
        @JvmField val ProgressBarColor = IntSetting(key = "progress_bar_color", defValue = 0)
        @JvmField val CommentImageSaveEnhanced = BooleanSetting(key = "comment_image_save_enhanced")
        @JvmField val LiveDanmakuFilter = BooleanSetting(key = "live_danmaku_filter")
        @JvmField val CommentExpandAll = BooleanSetting(key = "comment_expand_all")
        @JvmField val VideoSpeedPresets = BooleanSetting(key = "video_speed_presets")
        @JvmField val SubtitlePosition = IntSetting(key = "subtitle_position", defValue = 0)
        @JvmField val CommentFontSize = IntSetting(key = "comment_font_size", defValue = 0)
        @JvmField val LiveAutoReconnect = BooleanSetting(key = "live_auto_reconnect")
        @JvmField val PlayerLongPressSpeed = FloatSetting(key = "player_long_press_speed", defValue = 0f)
        @JvmField val CommentReplyHighlight = BooleanSetting(key = "comment_reply_highlight")
        @JvmField val DanmakuFontOutline = BooleanSetting(key = "danmaku_font_outline")
        @JvmField val VideoLoopCount = IntSetting(key = "video_loop_count", defValue = 0)
        @JvmField val PlayerBrightnessMemory = BooleanSetting(key = "player_brightness_memory")
        @JvmField val VideoRotationLock = BooleanSetting(key = "video_rotation_lock")
        @JvmField val CommentSortNewest = BooleanSetting(key = "comment_sort_newest")
        @JvmField val DanmakuAreaTop = BooleanSetting(key = "danmaku_area_top")
        @JvmField val VideoCacheSize = IntSetting(key = "video_cache_size", defValue = 0)
        @JvmField val CommentImagePreview = BooleanSetting(key = "comment_image_preview")
        @JvmField val DanmakuSendPosition = IntSetting(key = "danmaku_send_position", defValue = 0)
        @JvmField val PlayerOverlayOpacity = IntSetting(key = "player_overlay_opacity", defValue = 100)


    // region Group: 首页
    @JvmField val ShowingBottomItems =
        StringSetSetting(key = "showing_bottom_items", defValue = setOf(Constants.ALL_VALUE))
    @JvmField val HidedHomeTab = StringSetSetting(key = "customize_home_tab")
    @JvmField val FilterHomeRecommend = StringSetSetting(key = "customize_home_recommend")
    @JvmField val HomeFilterApplyToVideo = BooleanSetting(key = "home_filter_apply_to_relate")
    @JvmField val HomeFilterApplyToPopular = BooleanSetting(key = "home_filter_apply_to_popular")
    @JvmField val HomeFilterApplyToStory = BooleanSetting(key = "home_filter_apply_to_story")
    @JvmField val LowPlayCountLimit = LongSetting(key = "hide_low_play_count_recommend_limit")
    @JvmField val ShortDurationLimit = IntSetting(key = "hide_short_duration_recommend_limit")
    @JvmField val LongDurationLimit = IntSetting(key = "hide_long_duration_recommend_limit")
    @JvmField val ShortDurationLimitStory = IntSetting(key = "hide_short_duration_story_limit")
    @JvmField val LongDurationLimitStory = IntSetting(key = "hide_long_duration_story_limit")
    @JvmField val HomeRcmdFilterTitle = StringSetSetting(key = "home_filter_keywords_title")
    @JvmField val HomeRcmdFilterTitleRegexMode = BooleanSetting(key = "home_filter_title_regex_mode")
    @JvmField val HomeRcmdFilterReason = StringSetSetting(key = "home_filter_keywords_reason")
    @JvmField val HomeRcmdFilterReasonRegexMode = BooleanSetting(key = "home_filter_reason_regex_mode")
    @JvmField val HomeRcmdFilterUid = StringSetSetting(key = "home_filter_keywords_uid")
    @JvmField val HomeRcmdFilterUp = StringSetSetting(key = "home_filter_keywords_up")
    @JvmField val HomeRcmdFilterUpRegexMode = BooleanSetting(key = "home_filter_up_regex_mode")
    @JvmField val HomeRcmdFilterCategory = StringSetSetting(key = "home_filter_keywords_category")
    @JvmField val HomeRcmdFilterChannel = StringSetSetting(key = "home_filter_keywords_channel")
    @JvmField val HomeDisableAutoRefresh = BooleanSetting(key = "disable_auto_refresh")
    @JvmField val AddBangumi = BooleanSetting(key = "add_bangumi", needReboot = true)
    @JvmField val AddMovie = BooleanSetting(key = "add_movie", needReboot = true)
    @JvmField val AddKorea = BooleanSetting(key = "add_korea", needReboot = true)
    @JvmField val PurifyGame = BooleanSetting(key = "purify_game", needReboot = true)
    @JvmField val Drawer = BooleanSetting(key = "drawer")
    @JvmField val DisableHomeStory = BooleanSetting(key = "disable_main_page_story", needReboot = true)
    @JvmField val BlockTopActivity =
        BooleanSetting(key = "block_top_activity", needReboot = true, onChange = { value, _ ->
            if (value) deleteTopActivityEntrance()
        })
    @JvmField val BlockRecommendGuidance = BooleanSetting(key = "block_recommend_guidance", needReboot = true)
    @JvmField val BlockPopularTopEntrance = BooleanSetting(key = "block_popular_top_entrance")
    @JvmField val BlockPopularTopicList = BooleanSetting(key = "block_popular_topic_list")
    @JvmField val BlockPopularRcmdUp = BooleanSetting(key = "block_popular_rcmd_up")
    @JvmField val BlockPopularLive = BooleanSetting(key = "block_popular_live")
    @JvmField val BlockHomeRecentUsed = BooleanSetting(key = "block_home_recent_used")
    @JvmField val PegasusCoverRatio = StringSetting(key = "pegasus_cover_ratio", defValue = "0", needReboot = true)


    // region Group: 动态页
    @JvmField val DynPreferVideoTab = BooleanSetting(key = "prefer_video_tab")
    @JvmField val DynPurifyCity = BooleanSetting(key = "purify_city")
    @JvmField val DynPurifyCampus = BooleanSetting(key = "purify_campus")
    @JvmField val DynRmTopicOfAll = BooleanSetting(key = "customize_dynamic_all_rm_topic")
    @JvmField val DynRmUpOfAll = BooleanSetting(key = "customize_dynamic_all_rm_up")
    @JvmField val DynRmUpOfVideo = BooleanSetting(key = "customize_dynamic_video_rm_up")
    @JvmField val DynFilterApplyTopVideo = BooleanSetting(key = "filter_apply_to_video")
    @JvmField val DynRmBlocked = BooleanSetting(key = "customize_dynamic_rm_blocked")
    @JvmField val DynRmAdLink = BooleanSetting(key = "customize_dynamic_rm_ad_link")
    @JvmField val DynRmUpReservation = BooleanSetting(key = "customize_dynamic_rm_up_reservation")
    @JvmField val DynPurifyType = StringSetSetting(key = "customize_dynamic_type")
    @JvmField val DynPurifyContent = StringSetSetting(key = "customize_dynamic_keyword_content")
    @JvmField val DynPurifyContentRegexMode = BooleanSetting(key = "dynamic_content_regex_mode")
    @JvmField val DynPurifyUp = StringSetSetting(key = "customize_dynamic_keyword_upname")
    @JvmField val DynPurifyUid = StringSetSetting(key = "customize_dynamic_keyword_uid")
    @JvmField val DynPurifyTopic = StringSetSetting(key = "customize_dynamic_keyword_topic")
    @JvmField val DynForceOldTabStyle = BooleanSetting(key = "dynamic_force_old_tab", needReboot = true)
    @JvmField val DynRmCm = BooleanSetting(key = "dynamic_rm_cm")
    @JvmField val DynRmStory = BooleanSetting(key = "dynamic_rm_story")
    @JvmField val DynNoUpRecall = BooleanSetting(key = "dynamic_no_up_recall", needReboot = true)


    // region Group: 我的�?
    @JvmField val DrawerStyle = StringSetting(key = "drawer_style_value", defValue = "0")
    @JvmField val PurifyDrawerRedDot = BooleanSetting(key = "purify_drawer_reddot")
    @JvmField val RemoveVipSection = BooleanSetting(key = "remove_vip_section")
    @JvmField val ShowingDrawerItems =
        StringSetSetting(key = "showing_drawer_items", defValue = setOf(Constants.ALL_VALUE))
    @JvmField val SwitchDarkTipsDialog = BooleanSetting(key = "switch_dark_dialog")
    @JvmField val AddChannel = BooleanSetting(key = "add_channel", needReboot = true)
    @JvmField val AddPodcast = BooleanSetting(key = "add_podcast")
    @JvmField val BlockTips = BooleanSetting(key = "block_tips")


    // region Group: 直播�?
    @JvmField val ForbidSwitchLiveRoom = BooleanSetting(key = "forbid_switch_live_room")
    @JvmField val DisableLiveRoomDoubleClick = BooleanSetting(key = "disable_live_room_double_click")
    @JvmField val PurifyLivePopups = StringSetSetting(key = "purify_live_popups")
    @JvmField val RemoveLiveMask = BooleanSetting(key = "remove_live_mask")
    @JvmField val DefaultMaxQn = BooleanSetting(key = "default_max_qn")
    @JvmField val DisableSlideLeft = BooleanSetting(key = "disable_slide_left")
    @JvmField val DisableAutoFloat = BooleanSetting(key = "disable_auto_float")
    @JvmField val RemoveLiveWatermark = BooleanSetting(key = "remove_live_watermark")
    @JvmField val LiveNoBlock = BooleanSetting(key = "live_no_block")
    @JvmField val LiveAutoSign = BooleanSetting(key = "live_auto_sign")


    // region Group: 视频详情�?
    @JvmField val AutoLike = BooleanSetting(key = "auto_like")
    @JvmField val SaveCommentImage = BooleanSetting(key = "save_comment_image")
    @JvmField val UnlockPlayLimit = BooleanSetting(key = "play_arc_conf")
    @JvmField val ReplaceStoryVideo = BooleanSetting(key = "replace_story_video")
    @JvmField val DisableStoryFull = BooleanSetting(key = "disable_story_full")
    @JvmField @Deprecated("replaced by RemoveVideoPopups") val RemoveCmdDms =
        BooleanSetting(key = "remove_video_cmd_dms")
    @JvmField val RemoveVideoPopups = StringSetSetting(key = "remove_video_popups")
    @JvmField val BlockWordSearch = BooleanSetting(key = "block_word_search")
    @JvmField val BlockCommentGuide = BooleanSetting(key = "block_comment_guide")
    @JvmField val BlockVideoComment = BooleanSetting(key = "block_video_comment")
    @JvmField val BlockUpRcmdAds = BooleanSetting(key = "block_up_rcmd_ads")
    @JvmField val BlockBangumiPageAds = BooleanSetting(key = "block_bangumi_page_ads")
    @JvmField val RemoveRelatePromote = BooleanSetting(key = "remove_video_relate_promote")
    @JvmField val RemoveRelateOnlyAv =
        BooleanSetting(key = "remove_video_relate_only_av", dependency = RemoveRelatePromote)
    @JvmField val RemoveRelateNothing =
        BooleanSetting(key = "remove_video_relate_nothing", dependency = RemoveRelateOnlyAv)
    @JvmField val RemoveRelateCharge = BooleanSetting("remove_video_relate_charge")
    @JvmField val DisableAutoSelect = BooleanSetting(key = "disable_auto_select")
    @JvmField val DisableAutoSubscribe = BooleanSetting(key = "disable_auto_subscribe")
    @JvmField val FilterStory = StringSetSetting(key = "filter_story")
    @JvmField val BlockDmFeedback = BooleanSetting(key = "block_dm_feedback")
    @JvmField val BlockFanGuide = BooleanSetting(key = "block_fan_guide")
    @JvmField val RemoveChargeButton = BooleanSetting(key = "remove_elec_button")
    @JvmField val BlockLiveOrder = BooleanSetting(key = "block_live_order")
    @JvmField val BlockActivityTab = BooleanSetting(key = "block_activity_tab")
    @JvmField val ForceOldFav = BooleanSetting(key = "old_fav", needReboot = true)
    @JvmField val BlockOnlyAtComment = BooleanSetting(key = "block_comment_only_at")
    @JvmField val BlockCommentGoods = BooleanSetting(key = "block_comment_goods")
    @JvmField val BlockCommentUid = StringSetSetting(key = "block_comment_uid")
    @JvmField val BlockCommentUp = StringSetSetting(key = "block_comment_up")
    @JvmField val BlockCommentUpRegexMode = BooleanSetting(key = "block_comment_up_regex_mode")
    @JvmField val BlockCommentContent = StringSetSetting(key = "block_comment_content")
    @JvmField val BlockCommentContentRegexMode = BooleanSetting(key = "block_comment_content_regex_mode")
    @JvmField val BlockCommentUpLevel = IntSetting(key = "block_comment_up_level")
    @JvmField val ExternalDownloader = BooleanSetting(key = "external_downloader")
    @JvmField val ExternalDownloaderName =
        StringSetting(key = "external_downloader_name", defValue = "com.junkfood.seal")
    @JvmField val NoColorfulDanmaku = BooleanSetting(key = "no_colorful_danmaku")
    @JvmField val DanmakuFilterKeywords = StringSetSetting(key = "danmaku_filter_keywords")
    @JvmField val DanmakuFilterRegexMode = BooleanSetting(key = "danmaku_filter_regex_mode")
    @JvmField val DanmakuFilterMinLength = IntSetting(key = "danmaku_filter_min_length", defValue = 0)
    @JvmField val DanmakuOpacity = IntSetting(key = "danmaku_opacity", defValue = 0)
    @JvmField val DanmakuMaxOnScreen = IntSetting(key = "danmaku_max_on_screen", defValue = 0)
    @JvmField val DanmakuFontSizeScale = FloatSetting(key = "danmaku_font_size_scale", defValue = 0f)
    @JvmField val DanmakuTimeOffset = IntSetting(key = "danmaku_time_offset", defValue = 0)
    @JvmField val DanmakuFilterPool = IntSetting(key = "danmaku_filter_pool", defValue = 0)
    @JvmField val DanmakuSpeed = IntSetting(key = "danmaku_speed", defValue = 0)
    @JvmField val DanmakuArea = IntSetting(key = "danmaku_area", defValue = 0)
    @JvmField val DanmakuHighlightKeywords = StringSetSetting(key = "danmaku_highlight_keywords")
    @JvmField val DanmakuHighlightColor = IntSetting(key = "danmaku_highlight_color", defValue = 0xFFFF0000.toInt())
    @JvmField val DefaultAspectRatio = IntSetting(key = "default_aspect_ratio", defValue = 0)
    @JvmField val AutoPauseOnBackground = BooleanSetting(key = "auto_pause_on_background")
    @JvmField val RememberVideoPosition = BooleanSetting(key = "remember_video_position")
    @JvmField val VideoBookmark = BooleanSetting(key = "video_bookmark")
    @JvmField val CommentTranslate = BooleanSetting(key = "comment_translate")
    @JvmField val AutoSkipIntro = BooleanSetting(key = "auto_skip_intro")
    @JvmField val AutoSkipIntroDuration = IntSetting(key = "auto_skip_intro_duration", defValue = 0)
    @JvmField val AutoSkipOutro = BooleanSetting(key = "auto_skip_outro")
    @JvmField val AutoSkipOutroDuration = IntSetting(key = "auto_skip_outro_duration", defValue = 0)
    @JvmField val VideoScreenshot = BooleanSetting(key = "video_screenshot")
    @JvmField val VideoScreenshotShare = BooleanSetting(key = "video_screenshot_share")
    @JvmField val VideoLoopSegment = BooleanSetting(key = "video_loop_segment")
    @JvmField val SpeedBadge = BooleanSetting(key = "speed_badge")

    @JvmField val CommentSortByTime = BooleanSetting(key = "comment_sort_by_time")
    @JvmField val ShowCommentIpLocation = BooleanSetting(key = "show_comment_ip_location")
    @JvmField val ShowCommentFloor = BooleanSetting(key = "show_comment_floor")
    @JvmField val ShowCommentReplyCount = BooleanSetting(key = "show_comment_reply_count")
    @JvmField val ShowVideoAvBvId = BooleanSetting(key = "show_video_av_bv_id")
    @JvmField val ShowCodecInfo = BooleanSetting(key = "show_codec_info")
    @JvmField val FakeNotInMultiWindow = BooleanSetting(key = "fake_not_in_multi_window")
    @JvmField val BlockCommentFeedback = BooleanSetting(key = "block_comment_feedback")
    @JvmField val NotLockOrientation = BooleanSetting(key = "not_lock_orientation")
    @JvmField val CheckComment = BooleanSetting(key = "check_comment")
    @JvmField val StoryUIStyle = StringSetting(key = "story_ui_style", defValue = "0")
    @JvmField val UnlockGif = BooleanSetting(key = "unlock_gif")
    @JvmField val TimeAirborne = BooleanSetting(key = "time_airborne")
    @JvmField val OldDmPanel = BooleanSetting(key = "old_dm_panel")
    @JvmField val BlockEndpageCharge = BooleanSetting(key = "block_endpage_charge")
    @JvmField val BlockRelatedGames = BooleanSetting(key = "block_related_games")
    @JvmField val AutoExpandDesc = BooleanSetting(key = "auto_expand_desc")
    @JvmField val HideFloatingButton = BooleanSetting(key = "hide_floating_button")
    @JvmField val LoopPlay = BooleanSetting(key = "loop_play")


    // region Group: 用户空间�?
    @JvmField val FixSpace = BooleanSetting(key = "fix_space", defValue = true)
    @JvmField val CustomizeSpace = StringSetSetting(key = "customize_space")
    @JvmField val AddArticleTab = BooleanSetting(key = "add_article_tab")
    @JvmField val IgnoreBlacklist = BooleanSetting(key = "ignore_blacklist")
    @JvmField val UidCopyNoPrefix = BooleanSetting(key = "uid_copy_no_prefix")
    @JvmField val CommentAnonymousMode = BooleanSetting(key = "comment_anonymous_mode")
    @JvmField val DanmakuSendDuration = IntSetting(key = "danmaku_send_duration", defValue = 0)
    @JvmField val LiveGiftMerge = BooleanSetting(key = "live_gift_merge")
    @JvmField val PlaybackSpeedStep = FloatSetting(key = "playback_speed_step", defValue = 0.25f)


    // region Group: 搜索�?
    @JvmField @Deprecated("replaced by PurifySearchTypes") val PurifySearch = BooleanSetting(key = "purify_search")
    @JvmField val PurifySearchTypes = StringSetSetting(key = "purify_search_types")
    @JvmField val SearchBangumi = BooleanSetting(key = "search_area_bangumi")
    @JvmField val SearchMovie = BooleanSetting(key = "search_area_movie")
    @JvmField val FilterSearchType = StringSetSetting(key = "filter_search_type")
    @JvmField val FilterSearchContent = StringSetSetting(key = "filter_search_content")
    @JvmField val FilterSearchContentRegexMode = BooleanSetting(key = "filter_search_content_regex")
    @JvmField val FilterSearchUp = StringSetSetting(key = "filter_search_up")
    @JvmField val FilterSearchUpRegexMode = BooleanSetting(key = "filter_search_up_regex")
    @JvmField val FilterSearchUid = StringSetSetting(key = "filter_search_uid")


    // region Group: 字幕
    @JvmField val AutoGenerateSubtitle = BooleanSetting(key = "auto_generate_subtitle")
    @JvmField val AutoSelectAISubtitle = BooleanSetting(key = "auto_select_ai_subtitle")
    @JvmField val EnableCustomSubtitleStyle = BooleanSetting(key = "custom_subtitle")
    @JvmField val RemoveSubtitleBg = BooleanSetting(key = "subtitle_remove_bg", defValue = true)
    @JvmField val BoldSubtitleText = BooleanSetting(key = "subtitle_bold", defValue = true)
    @JvmField val SubtitleFontSizePortrait = IntSetting(key = "subtitle_font_size_portrait")
    @JvmField val SubtitleFontSizeLandscape = IntSetting(key = "subtitle_font_size_landscape")
    @JvmField val SubtitleFillColor = StringSetting(key = "subtitle_font_color2", defValue = "FFFFFFFF")
    @JvmField val SubtitleStrokeColor = StringSetting(key = "subtitle_stroke_color", defValue = "FF000000")
    @JvmField val SubtitleStrokeWidth = FloatSetting(key = "subtitle_stroke_width", defValue = 5.0f)
    @JvmField val SubtitleOffset = IntSetting(key = "subtitle_offset")
    @JvmField val SubtitleTranslateServer = StringSetting(key = "subtitle_translate_server", defValue = "microsoft")
    @JvmField val SubtitleImportSave = BooleanSetting(key = "subtitle_import_save")


    // region Group: 杂项
    @JvmField val DisableTeenagerDialog = BooleanSetting(key = "teenagers_mode_dialog")
    @JvmField val CommentCopy = BooleanSetting(key = "comment_copy")
    @JvmField val EnhanceCommentCopy = BooleanSetting(key = "comment_copy_enhance", dependency = CommentCopy)
    @JvmField val BlockUpdate = BooleanSetting(key = "block_update")
    @JvmField val CustomUpdate = BooleanSetting(key = "custom_update", defValue = true)
    @JvmField val BlockFollowButton = StringSetSetting(key = "block_follow_button")
    @JvmField val CustomTheme = BooleanSetting(key = "custom_theme")
    @JvmField val Skin = BooleanSetting(key = "skin")
    @JvmField val TextFoldCommentMaxLines =
        IntSetting(key = "text_fold_comment_max_lines", defValue = Constants.DEF_COMMENT_MAX_LINES)
    @JvmField val TextFoldDynMaxLines =
        IntSetting(key = "text_fold_dyn_max_lines", defValue = Constants.DEF_DYN_MAX_LINES)
    @JvmField val TextFoldDynLinesToAll =
        IntSetting(key = "text_fold_dyn_lines_to_all", defValue = Constants.DEF_DYN_LINES_TO_ALL)
    @JvmField val DelayDownloadModules =
        BooleanSetting(key = "delay_download_modules", defValue = true, onChange = { value, async ->
            if (value) if (async) {
                Utils.async { deleteModuleResources() }
            } else {
                deleteModuleResources()
        }
        })
    @JvmField val MusicNotification = BooleanSetting(key = "music_notification", needReboot = true)
    @JvmField val PurifyShare = BooleanSetting(key = "purify_share")
    @JvmField val FuckMiniProgram = BooleanSetting(key = "mini_program")
    @JvmField val NumberFormat = BooleanSetting(key = "number_format")
    @JvmField val AutoReceiveCoupon = BooleanSetting(key = "auto_receive_coupon")
    @JvmField val DisplaySize = StringSetting(key = "display_size", defValue = "0", needReboot = true)
    @JvmField val CustomSplash = BooleanSetting(key = "custom_splash")
    @JvmField val CustomSplashLogo = BooleanSetting(key = "custom_splash_logo")
    @JvmField val FullSplash = BooleanSetting(key = "full_splash")
    @JvmField val EnableAv = BooleanSetting(key = "enable_av", needReboot = true)
    @JvmField val EnableDocProvider = BooleanSetting(key = "enable_doc_provider", onChange = { value, _ ->
        changeComponentState(BiliDocumentsProvider::class.java, value)
    })
    @JvmField val DisableAvif = BooleanSetting(key = "disable_avif", needReboot = true)
    @JvmField val PurifySplash = BooleanSetting(key = "purify_splash", onChange = { value, async ->
        if (value) if (async) {
            Utils.async { clearSplashConfigCache() }
        } else {
            clearSplashConfigCache()
    }
    })
    @JvmField val DisallowCollectPrivacyInfo = BooleanSetting(key = "disallow_collect_privacy_info", needReboot = true)
    @JvmField val DisableWebViewNonOfficialAlert = BooleanSetting(key = "disable_non_official_alert")


    // region Group: 非配置项
    @JvmField val LosslessEnabled = BooleanSetting(key = "lossless_enabled")
    @JvmField val BgPlayingEnabled = BooleanSetting(key = "bg_playing_enabled")
    @JvmField val CustomColor = IntSetting(key = "biliroaming_custom_color", defValue = Color.WHITE)
    @JvmField val SkinJson = StringSetting(key = "skin_json", dependency = Skin)
    @JvmField val SelectedPlaybackSpeed = FloatSetting(key = "selected_playback_speed")
    @JvmField val CommentGifAutoPlay = BooleanSetting(key = "comment_gif_auto_play")
    @JvmField val DanmakuBatchDelete = BooleanSetting(key = "danmaku_batch_delete")
    @JvmField val PlayerScreenshotFormat = IntSetting(key = "player_screenshot_format", defValue = 0)
    @JvmField val LiveRoomAutoEnter = StringSetting(key = "live_room_auto_enter")
    @JvmField val CommentImageAutoLoad = BooleanSetting(key = "comment_image_auto_load")
    @JvmField val DanmakuBatchReport = BooleanSetting(key = "danmaku_batch_report")
    @JvmField val VideoThumbnailPreview = BooleanSetting(key = "video_thumbnail_preview")
    @JvmField val VideoAutoPauseOnScroll = BooleanSetting(key = "video_auto_pause_on_scroll")
    @JvmField val DanmakuFontStyle = IntSetting(key = "danmaku_font_style", defValue = 0)
    @JvmField val DanmakuSendAnimation = BooleanSetting(key = "danmaku_send_animation")
    @JvmField val PlayerBackgroundDim = IntSetting(key = "player_background_dim", defValue = 0)
    @JvmField val VideoAutoNext = BooleanSetting(key = "video_auto_next")
    @JvmField val DanmakuFilterByUser = StringSetSetting(key = "danmaku_filter_by_user")
    @JvmField val PlayerGestureVolume = BooleanSetting(key = "player_gesture_volume")
    @JvmField val VideoAutoSave = BooleanSetting(key = "video_auto_save")
    @JvmField val CommentAutoReply = StringSetting(key = "comment_auto_reply")
    @JvmField val CommentEmojiKeyboard = BooleanSetting(key = "comment_emoji_keyboard")
    @JvmField val LiveRoomAutoMute = BooleanSetting(key = "live_room_auto_mute")
    @JvmField val PlayerGestureBrightness = BooleanSetting(key = "player_gesture_brightness")
    @JvmField val DanmakuFilterByColor = StringSetSetting(key = "danmaku_filter_by_color")
    @JvmField val DanmakuSendPreview = BooleanSetting(key = "danmaku_send_preview")
    @JvmField val SubtitleDownload = BooleanSetting(key = "subtitle_download")
    @JvmField val LiveStreamClip = BooleanSetting(key = "live_stream_clip")
    @JvmField val PlayerPipSize = IntSetting(key = "player_pip_size", defValue = 0)
    @JvmField val LiveDanmakuFont = IntSetting(key = "live_danmaku_font", defValue = 0)
    @JvmField val AutoSkipFiller = BooleanSetting(key = "auto_skip_filler")
    @JvmField val PlayerScreenshotQuality = IntSetting(key = "player_screenshot_quality", defValue = 100)
    @JvmField val VideoAutoShare = BooleanSetting(key = "video_auto_share")
    @JvmField val CommentStickerKeyboard = BooleanSetting(key = "comment_sticker_keyboard")
    @JvmField val DanmakuSendHistory = BooleanSetting(key = "danmaku_send_history")
    @JvmField val PlayerControlLayout = IntSetting(key = "player_control_layout", defValue = 0)
    @JvmField val LiveRoomBackground = IntSetting(key = "live_room_background", defValue = 0)
    @JvmField val VideoBufferSize = IntSetting(key = "video_buffer_size", defValue = 0)
    @JvmField val LiveRoomGiftEffect = BooleanSetting(key = "live_room_gift_effect")
    @JvmField val AudioOnlyMode = BooleanSetting(key = "audio_only_mode")
    @JvmField val MiniPlayerSize = IntSetting(key = "mini_player_size", defValue = 0)
    @JvmField val DynamicAutoRefresh = BooleanSetting(key = "dynamic_auto_refresh")
    @JvmField val CommentVoiceInput = BooleanSetting(key = "comment_voice_input")
    @JvmField val VideoDownloadQuality = IntSetting(key = "video_download_quality", defValue = 0)
    @JvmField val LiveDanmakuColor = IntSetting(key = "live_danmaku_color", defValue = 0)
    @JvmField val SearchAutoComplete = BooleanSetting(key = "search_auto_complete")
    @JvmField val PlayerProgressBarStyle = IntSetting(key = "player_progress_bar_style", defValue = 0)
    @JvmField val HomeShortcut = StringSetSetting(key = "home_shortcut")
    @JvmField val VideoEndAction = IntSetting(key = "video_end_action", defValue = 0)
    @JvmField val PlayerGestureSeek = BooleanSetting(key = "player_gesture_seek")
    @JvmField val VideoAutoPauseDetect = BooleanSetting(key = "video_auto_pause_detect")
    @JvmField val CommentGifSticker = BooleanSetting(key = "comment_gif_sticker")
    @JvmField val DanmakuSmartFilter = BooleanSetting(key = "danmaku_smart_filter")
    @JvmField val CommentAutoPin = BooleanSetting(key = "comment_auto_pin")
    @JvmField val VideoAutoDownload = BooleanSetting(key = "video_auto_download")
    @JvmField val DynamicAutoScroll = BooleanSetting(key = "dynamic_auto_scroll")
    @JvmField val VideoAutoSpeed = BooleanSetting(key = "video_auto_speed")
    @JvmField val DanmakuHighlightUser = StringSetSetting(key = "danmaku_highlight_user")
    @JvmField val CommentImageCompress = BooleanSetting(key = "comment_image_compress")
    @JvmField val PlayerSubtitleSync = IntSetting(key = "player_subtitle_sync", defValue = 0)
    @JvmField val LiveAutoRecord = BooleanSetting(key = "live_auto_record")
    @JvmField val VideoSmartPreload = BooleanSetting(key = "video_smart_preload")
    @JvmField val HomeWidgetCustom = BooleanSetting(key = "home_widget_custom")
    @JvmField val SearchFilterQuality = BooleanSetting(key = "search_filter_quality")
    @JvmField val DynamicAutoLike = BooleanSetting(key = "dynamic_auto_like")
    @JvmField val DanmakuTranslate = BooleanSetting(key = "danmaku_translate")
    @JvmField val CommentSortDefault = IntSetting(key = "comment_sort_default", defValue = 0)
    @JvmField val PlayerGestureDoubleTap = IntSetting(key = "player_gesture_double_tap", defValue = 0)
    @JvmField val VideoAutoResume = BooleanSetting(key = "video_auto_resume")
    @JvmField val LiveDanmakuSpeed = IntSetting(key = "live_danmaku_speed", defValue = 0)
    @JvmField val HomeFeedCache = BooleanSetting(key = "home_feed_cache")
    @JvmField val SearchAutoCorrect = BooleanSetting(key = "search_auto_correct")
    @JvmField val DynamicPinTop = BooleanSetting(key = "dynamic_pin_top")
    @JvmField val DanmakuFontFamily = IntSetting(key = "danmaku_font_family", defValue = 0)
    @JvmField val CommentAutoLike = BooleanSetting(key = "comment_auto_like")
    @JvmField val VideoAutoQuality = IntSetting(key = "video_auto_quality", defValue = 0)
    @JvmField val CommentSortReverse = BooleanSetting(key = "comment_sort_reverse")
    @JvmField val PlayerGestureLongPress = IntSetting(key = "player_gesture_long_press", defValue = 0)
    @JvmField val VideoAutoSkipCredits = BooleanSetting(key = "video_auto_skip_credits")
    @JvmField val LiveDanmakuFilterKeywords = StringSetSetting(key = "live_danmaku_filter_keywords")
    @JvmField val HomeFeedAutoRefresh = BooleanSetting(key = "home_feed_auto_refresh")
    @JvmField val DynamicAutoForward = BooleanSetting(key = "dynamic_auto_forward")
    @JvmField val SearchAutoSuggest = BooleanSetting(key = "search_auto_suggest")
    @JvmField val DanmakuSendDelay = IntSetting(key = "danmaku_send_delay", defValue = 0)
    @JvmField val PlayerControlAutoHide = IntSetting(key = "player_control_auto_hide", defValue = 3)
    @JvmField val VideoAutoPauseOnCall = BooleanSetting(key = "video_auto_pause_on_call")
    @JvmField val LiveRoomAutoFollow = BooleanSetting(key = "live_room_auto_follow")
    @JvmField val DynamicAutoTranslate = BooleanSetting(key = "dynamic_auto_translate")
    @JvmField val CommentLineSpacing = FloatSetting(key = "comment_line_spacing", defValue = 1.0f)
    @JvmField val DanmakuFontWeight = IntSetting(key = "danmaku_font_weight", defValue = 0)
    @JvmField val VideoChaptersAutoSkip = BooleanSetting(key = "video_chapters_auto_skip")
    @JvmField val PlayerBrightnessAuto = BooleanSetting(key = "player_brightness_auto")
    @JvmField val HomeFeedSort = IntSetting(key = "home_feed_sort", defValue = 0)
    @JvmField val DynamicAutoSave = BooleanSetting(key = "dynamic_auto_save")
    @JvmField val CommentDraftAutoSave = BooleanSetting(key = "comment_draft_auto_save")
    @JvmField val DanmakuSendConfirm = BooleanSetting(key = "danmaku_send_confirm")
    @JvmField val PlayerGestureTripleTap = IntSetting(key = "player_gesture_triple_tap", defValue = 0)
    @JvmField val VideoAutoSkipPreview = BooleanSetting(key = "video_auto_skip_preview")
    @JvmField val LiveDanmakuMerge = BooleanSetting(key = "live_danmaku_merge")
    @JvmField val HomeFeedInfiniteScroll = BooleanSetting(key = "home_feed_infinite_scroll")
    @JvmField val DynamicAutoBlock = BooleanSetting(key = "dynamic_auto_block")
    @JvmField val SearchHistoryClear = BooleanSetting(key = "search_history_clear")
    @JvmField val CommentHighlightSelf = BooleanSetting(key = "comment_highlight_self")
    @JvmField val DanmakuSpeedAdjust = FloatSetting(key = "danmaku_speed_adjust", defValue = 1.0f)
    @JvmField val PlayerControlOpacity = IntSetting(key = "player_control_opacity", defValue = 100)
    @JvmField val VideoAutoPauseOnLock = BooleanSetting(key = "video_auto_pause_on_lock")
    @JvmField val LiveRoomAutoGift = BooleanSetting(key = "live_room_auto_gift")
    @JvmField val DynamicAutoMute = BooleanSetting(key = "dynamic_auto_mute")
    @JvmField val CommentAutoDelete = BooleanSetting(key = "comment_auto_delete")
    @JvmField val DanmakuFilterDuplicate = BooleanSetting(key = "danmaku_filter_duplicate")
    @JvmField val VideoSmartPause = BooleanSetting(key = "video_smart_pause")
    @JvmField val PlayerScreenshotAutoSave = BooleanSetting(key = "player_screenshot_auto_save")
    @JvmField val HomeFeedShuffle = BooleanSetting(key = "home_feed_shuffle")
    @JvmField val DynamicAutoRefreshInterval = IntSetting(key = "dynamic_auto_refresh_interval", defValue = 0)
    @JvmField val CommentEmojiAutoComplete = BooleanSetting(key = "comment_emoji_auto_complete")
    @JvmField val DanmakuPositionCustom = IntSetting(key = "danmaku_position_custom", defValue = 0)
    @JvmField val PlayerGesturePinch = BooleanSetting(key = "player_gesture_pinch")
    @JvmField val VideoAutoSkipEnding = BooleanSetting(key = "video_auto_skip_ending")
    @JvmField val LiveDanmakuBlockEmoji = BooleanSetting(key = "live_danmaku_block_emoji")
    @JvmField val HomeFeedAutoLoadMore = BooleanSetting(key = "home_feed_auto_load_more")
    @JvmField val DynamicAutoBookmark = BooleanSetting(key = "dynamic_auto_bookmark")
    @JvmField val SearchAutoFilter = StringSetSetting(key = "search_auto_filter")
    @JvmField val CommentHighlightKeyword = StringSetSetting(key = "comment_highlight_keyword")
    @JvmField val DanmakuBackgroundOpacity = IntSetting(key = "danmaku_background_opacity", defValue = 0)
    @JvmField val PlayerNightMode = BooleanSetting(key = "player_night_mode")
    @JvmField val VideoAutoPauseOnBattery = IntSetting(key = "video_auto_pause_on_battery", defValue = 0)
    @JvmField val LiveRoomAutoEnterFullscreen = BooleanSetting(key = "live_room_auto_enter_fullscreen")
    @JvmField val DynamicAutoLikeAll = BooleanSetting(key = "dynamic_auto_like_all")
    @JvmField val CommentSortPinned = BooleanSetting(key = "comment_sort_pinned")
    @JvmField val PlayerControlAnimation = BooleanSetting(key = "player_control_animation")
    @JvmField val VideoSmartResolution = BooleanSetting(key = "video_smart_resolution")
    @JvmField val HomeFeedMarkRead = BooleanSetting(key = "home_feed_mark_read")
    @JvmField val DynamicAutoReply = BooleanSetting(key = "dynamic_auto_reply")
    @JvmField val CommentAutoTranslateLive = BooleanSetting(key = "comment_auto_translate_live")
    @JvmField val DanmakuHideOnScroll = BooleanSetting(key = "danmaku_hide_on_scroll")
    @JvmField val PlayerGestureShake = BooleanSetting(key = "player_gesture_shake")
    @JvmField val VideoAutoSkipSponsor = BooleanSetting(key = "video_auto_skip_sponsor")
    @JvmField val LiveDanmakuFontSize = IntSetting(key = "live_danmaku_font_size", defValue = 0)
    @JvmField val HomeFeedAutoNight = BooleanSetting(key = "home_feed_auto_night")
    @JvmField val CommentSortByLength = BooleanSetting(key = "comment_sort_by_length")
    @JvmField val DanmakuSendQueue = BooleanSetting(key = "danmaku_send_queue")
    @JvmField val PlayerScreenshotShare = BooleanSetting(key = "player_screenshot_share")
    @JvmField val VideoAutoPauseOnHeadphone = BooleanSetting(key = "video_auto_pause_on_headphone")
    @JvmField val LiveRoomAutoMuteOnBackground = BooleanSetting(key = "live_room_auto_mute_on_background")
    @JvmField val DynamicAutoDelete = BooleanSetting(key = "dynamic_auto_delete")
    @JvmField val CommentHighlightVIP = BooleanSetting(key = "comment_highlight_vip")
    @JvmField val DanmakuFontStretch = FloatSetting(key = "danmaku_font_stretch", defValue = 1.0f)
    @JvmField val PlayerGestureShakeUndo = BooleanSetting(key = "player_gesture_shake_undo")
    @JvmField val VideoSmartCache = BooleanSetting(key = "video_smart_cache")
    @JvmField val HomeFeedAutoScroll = BooleanSetting(key = "home_feed_auto_scroll")
    @JvmField val DynamicAutoBlockUser = BooleanSetting(key = "dynamic_auto_block_user")
    @JvmField val DanmakuSendCooldown = IntSetting(key = "danmaku_send_cooldown", defValue = 0)
    @JvmField val PlayerGestureVolumeStep = IntSetting(key = "player_gesture_volume_step", defValue = 0)
    @JvmField val VideoAutoSkipTransition = BooleanSetting(key = "video_auto_skip_transition")
    @JvmField val LiveDanmakuAutoScroll = BooleanSetting(key = "live_danmaku_auto_scroll")
    @JvmField val HomeFeedAutoRefreshInterval = IntSetting(key = "home_feed_auto_refresh_interval", defValue = 0)
    @JvmField val DynamicAutoArchive = BooleanSetting(key = "dynamic_auto_archive")
    @JvmField val SearchAutoSuggestLimit = IntSetting(key = "search_auto_suggest_limit", defValue = 0)
    @JvmField val CommentHighlightModerator = BooleanSetting(key = "comment_highlight_moderator")
    @JvmField val PlayerScreenshotNotification = BooleanSetting(key = "player_screenshot_notification")
    @JvmField val VideoAutoPauseOnNotification = BooleanSetting(key = "video_auto_pause_on_notification")
    @JvmField val LiveRoomAutoReconnect = BooleanSetting(key = "live_room_auto_reconnect")
    @JvmField val DynamicAutoRepost = BooleanSetting(key = "dynamic_auto_repost")
    @JvmField val CommentSortByReply = BooleanSetting(key = "comment_sort_by_reply")
    @JvmField val PlayerControlGesture = IntSetting(key = "player_control_gesture", defValue = 0)
    @JvmField val VideoSmartBuffer = BooleanSetting(key = "video_smart_buffer")
    @JvmField val DanmakuHideOnPause = BooleanSetting(key = "danmaku_hide_on_pause")
    @JvmField val PlayerGestureRotate = BooleanSetting(key = "player_gesture_rotate")
    @JvmField val VideoAutoRepeatSegment = BooleanSetting(key = "video_auto_repeat_segment")
    @JvmField val LiveDanmakuSpeedControl = BooleanSetting(key = "live_danmaku_speed_control")
    @JvmField val DynamicAutoDeleteOld = BooleanSetting(key = "dynamic_auto_delete_old")
    @JvmField val SearchAutoCompleteHistory = BooleanSetting(key = "search_auto_complete_history")
    @JvmField val CommentHighlightNew = BooleanSetting(key = "comment_highlight_new")
    @JvmField val PlayerScreenshotPath = StringSetting(key = "player_screenshot_path")
    @JvmField val LiveRoomAutoFollowAll = BooleanSetting(key = "live_room_auto_follow_all")
    @JvmField val DynamicAutoBlockKeyword = StringSetSetting(key = "dynamic_auto_block_keyword")
    @JvmField val CommentAutoExpandShort = BooleanSetting(key = "comment_auto_expand_short")
    @JvmField val PlayerControlFadeOut = IntSetting(key = "player_control_fade_out", defValue = 3)
    @JvmField val VideoSmartQuality = BooleanSetting(key = "video_smart_quality")
    @JvmField val HomeFeedAutoRefreshOnFocus = BooleanSetting(key = "home_feed_auto_refresh_on_focus")
    @JvmField val DynamicAutoPinComment = BooleanSetting(key = "dynamic_auto_pin_comment")
    @JvmField val CommentAutoTranslate = BooleanSetting(key = "comment_auto_translate")
    @JvmField val DanmakuFontLetterSpacing = FloatSetting(key = "danmaku_font_letter_spacing", defValue = 0f)
    @JvmField val PlayerGestureDoubleTapSpeed = IntSetting(key = "player_gesture_double_tap_speed", defValue = 0)
    @JvmField val VideoAutoSkipMidroll = BooleanSetting(key = "video_auto_skip_midroll")
    @JvmField val LiveDanmakuMergeSimilar = BooleanSetting(key = "live_danmaku_merge_similar")
    @JvmField val HomeFeedAutoNightTheme = BooleanSetting(key = "home_feed_auto_night_theme")
    @JvmField val DynamicAutoBlockSensitive = BooleanSetting(key = "dynamic_auto_block_sensitive")
    @JvmField val SearchAutoCompleteTrending = BooleanSetting(key = "search_auto_complete_trending")
    @JvmField val CommentHighlightReply = BooleanSetting(key = "comment_highlight_reply")
    @JvmField val DanmakuFontLineHeight = FloatSetting(key = "danmaku_font_line_height", defValue = 1.0f)
    @JvmField val PlayerScreenshotFormatCustom = IntSetting(key = "player_screenshot_format_custom", defValue = 0)
    @JvmField val VideoAutoPauseOnSilence = BooleanSetting(key = "video_auto_pause_on_silence")
    @JvmField val LiveRoomAutoEnterPicture = BooleanSetting(key = "live_room_auto_enter_picture")
    @JvmField val DynamicAutoArchiveOld = BooleanSetting(key = "dynamic_auto_archive_old")
    @JvmField val CommentAutoExpandAll = BooleanSetting(key = "comment_auto_expand_all")
    @JvmField val DanmakuSendFontFamily = IntSetting(key = "danmaku_send_font_family", defValue = 0)
    @JvmField val PlayerControlAutoFade = BooleanSetting(key = "player_control_auto_fade")
    @JvmField val VideoSmartBitrate = BooleanSetting(key = "video_smart_bitrate")
    @JvmField val HomeFeedAutoNightThemeSchedule = BooleanSetting(key = "home_feed_auto_night_theme_schedule")
    @JvmField val DynamicAutoPinSelf = BooleanSetting(key = "dynamic_auto_pin_self")
    @JvmField val CommentAutoSortByLike = BooleanSetting(key = "comment_auto_sort_by_like")
    @JvmField val PlayerControlAutoHideTimeout = IntSetting(key = "player_control_auto_hide_timeout", defValue = 3)
    @JvmField val DynamicAutoPinAll = BooleanSetting(key = "dynamic_auto_pin_all")
    @JvmField val DynamicAutoArchiveAll = BooleanSetting(key = "dynamic_auto_archive_all")
    @JvmField val SearchAutoCompleteSuggest = BooleanSetting(key = "search_auto_complete_suggest")
    @JvmField val PlayerScreenshotSharePath = StringSetting(key = "player_screenshot_share_path")
    @JvmField val DynamicAutoBlockAllSensitive = BooleanSetting(key = "dynamic_auto_block_all_sensitive")
    @JvmField val PlayerGestureSwipeSpeed = BooleanSetting(key = "player_gesture_swipe_speed")
    @JvmField val LiveDanmakuFilterUser = StringSetSetting(key = "live_danmaku_filter_user")
    @JvmField val HomeFeedAutoNightBrightnessCustom = BooleanSetting(key = "home_feed_auto_night_brightness_custom")
    // endregion
}
